# Site settings
baseURL = "http://robotrobot.io/"
languageCode = "en-us"
title = "RobotRobot.io"
theme = "forty"
log = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "webmaster"
  description = "robots@ubiquibit.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
#  [params.error404]
#    heading = "Page couldn't be found"
#    text = "Please visit [this pg](/)"

  # Navigation Section
  [params.navigation]
    title = "RobotRobot"
    subtitle = ". io"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Experiences"
      url = "experiences"

    [[params.navigation.links]]
      name = "Contact"
      url = "http://localhost:1313/#contact"
    
    [[params.navigation.links]]
      name = "People"
      url = "people"
    
    [[params.navigation.links]]
      name = "Home"
      url = "#"

#    [[params.navigation.links]]
#      name = "site map"
#      url = "site"

  # Banner section
  [params.banner]
    # To change the background image on the homepg banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Kids Building Robots"
    subtitle = "Experiential Engineering. Technology for all."
    buttonText = "Learn more"
    image = "img100.jpg" 

  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Play"
      subtitle = "Robots & young engineers (ages 7+)"
      image = "site/play0.png"
      url = "site/play/"

    [[params.tiles.showcase]]
      title = "Build"
      subtitle = "Circuits & programming (ages 10+)"
      image = "site/build0.png"
      url = "site/build/"

    [[params.tiles.showcase]]
      title = "Experiences"
      subtitle = "Guided events, building robots"
      image = "pic03.jpg"
      url = "experiences"

    [[params.tiles.showcase]]
      title = "Prepare"
      subtitle = "Avid learning (ages 14+)"
      image = "site/prepare0.jpg"
      url = "site/prepare/"

  [params.site]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "All people included"
    p0 = "Young people learn."
    p1 = "Girls & boys."
    p2 = "Kids, teens & young adults."
    p3 = "Play, build, create."
    p4 = "Come hack with us."
    exp = "/experiences"

  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "robots@ubiquibit.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "robots@ubiquibit.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+1 608 535 9518"

    [[params.contact.address]]
    title = "RobotRobot.io"
    street = "505 S Rosa Rd"
    city = "Madison WI 53719"
    #country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "RobotRobot.io"

    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/robotrobot_io"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/robotrobot.io"
      label = "Facebook"

#    [[params.footer.social]]
#      icon = "fa-instagram"
#      url= "https://www.instagram.com"
#      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

#    [[params.footer.social]]
#      icon = "fa-linkedin"
#      url= "https://www.linkedin.com"
#      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"

